In [1]:
import numpy as np
import pandas as pd
pd.Timestamp.max
pd.Timestamp.min

Timestamp('2262-04-11 23:47:16.854775807')

Timestamp('1677-09-21 00:12:43.145224193')

In [13]:
df=pd.read_csv('../data/player.csv')
pd.to_datetime('today')
df['birthday']=pd.to_datetime(df['birthday'])
df.info()
df.head()

Timestamp('2025-11-01 22:46:49.011637')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11060 entries, 0 to 11059
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   player_api_id  11060 non-null  int64
 1   player_name    11060 non-null  object
 2   birthday       11060 non-null  datetime64[ns]
 3   height         11060 non-null  float64
 4   weight         11060 non-null  int64
dtypes: datetime64[ns](1), float64(1), int64(2), object(1)
memory usage: 432.2+ KB

   player_api_id         player_name   birthday  height  weight
0         505942  Aaron Appindangoye 1992-02-29  182.88     187
1         155782     Aaron Cresswell 1989-12-15  170.18     146
2         162549         Aaron Doran 1991-05-13  170.18     163
3          30572       Aaron Galindo 1982-05-08  182.88     198
4          23780        Aaron Hughes 1979-11-08  182.88     154

TypeError: 'Timestamp' object is not subscriptable

In [3]:
days=(pd.to_datetime('today')-df['birthday']).dt.days
days

0        12299
1        13105
2        12591
3        15883
4        16795
         ...
11055    17014
11056    14198
11057    16988
11058    16097
11059    15855
Name: birthday, Length: 11060, dtype: int64

In [6]:
current=pd.to_datetime('today')
df.birthday.map(lambda x:current-x)

#二
#df.birthday=pd.to_datetime(df.birthday)
#

0       12299 days 22:42:56.973946
1       13105 days 22:42:56.973946
2       12591 days 22:42:56.973946
3       15883 days 22:42:56.973946
4       16795 days 22:42:56.973946
                   ...
11055   17014 days 22:42:56.973946
11056   14198 days 22:42:56.973946
11057   16988 days 22:42:56.973946
11058   16097 days 22:42:56.973946
11059   15855 days 22:42:56.973946
Name: birthday, Length: 11060, dtype: timedelta64[ns]

In [18]:
df=pd.read_csv('../data/player.csv')
df.head()
df.birthday.map(lambda x:x[:7])#字符串切片切片

   player_api_id         player_name             birthday  height  weight
0         505942  Aaron Appindangoye  1992-02-29 00:00:00  182.88     187
1         155782     Aaron Cresswell  1989-12-15 00:00:00  170.18     146
2         162549         Aaron Doran  1991-05-13 00:00:00  170.18     163
3          30572       Aaron Galindo  1982-05-08 00:00:00  182.88     198
4          23780        Aaron Hughes  1979-11-08 00:00:00  182.88     154

0        1992-02
1        1989-12
2        1991-05
3        1982-05
4        1979-11
          ...
11055    1979-04
11056    1986-12
11057    1979-04
11058    1981-10
11059    1982-06
Name: birthday, Length: 11060, dtype: object

In [19]:
df.birthday.map(lambda x:x.strftime('%Y-%m'))

AttributeError: 'str' object has no attribute 'strftime'

In [15]:
df.assign(年龄=df.birthday.map(lambda x:pd.to_datetime('today').year-x.year))
df

       player_api_id          player_name   birthday  height  weight  年龄
0             505942   Aaron Appindangoye 1992-02-29  182.88     187  33
1             155782      Aaron Cresswell 1989-12-15  170.18     146  36
2             162549          Aaron Doran 1991-05-13  170.18     163  34
3              30572        Aaron Galindo 1982-05-08  182.88     198  43
4              23780         Aaron Hughes 1979-11-08  182.88     154  46
...              ...                  ...        ...     ...     ...  ..
11055          26357       Zoumana Camara 1979-04-03  182.88     168  46
11056         111182         Zsolt Laczko 1986-12-18  182.88     176  39
11057          36491            Zsolt Low 1979-04-29  180.34     154  46
11058          35506  Zurab Khizanishvili 1981-10-06  185.42     172  44
11059          39902   Zvjezdan Misimovic 1982-06-05  180.34     176  43

[11060 rows x 6 columns]

       player_api_id          player_name   birthday  height  weight
0             505942   Aaron Appindangoye 1992-02-29  182.88     187
1             155782      Aaron Cresswell 1989-12-15  170.18     146
2             162549          Aaron Doran 1991-05-13  170.18     163
3              30572        Aaron Galindo 1982-05-08  182.88     198
4              23780         Aaron Hughes 1979-11-08  182.88     154
...              ...                  ...        ...     ...     ...
11055          26357       Zoumana Camara 1979-04-03  182.88     168
11056         111182         Zsolt Laczko 1986-12-18  182.88     176
11057          36491            Zsolt Low 1979-04-29  180.34     154
11058          35506  Zurab Khizanishvili 1981-10-06  185.42     172
11059          39902   Zvjezdan Misimovic 1982-06-05  180.34     176

[11060 rows x 5 columns]

In [22]:
#显示球员的 年月日
df = pd.read_csv('../data/player.csv')
df.birthday[0]
df.birthday[0][:4]
df.birthday[0][5:7]
df.birthday[0][8:10]
df = pd.read_csv('../data/player.csv')
df.birthday=pd.to_datetime(df.birthday)
df.birthday[0].year
df.birthday[0].month
s=df.birthday[0].day
type(s)

'1992-02-29 00:00:00'

'1992'

'02'

'29'

1992

2

int

In [26]:
df.birthday[0].hour
df.birthday[0].minute
df.birthday[0].second
df.birthday[0].date()
df.birthday[0].time()

0

0

0

datetime.date(1992, 2, 29)

datetime.time(0, 0)

In [27]:
df.assign(age=df.birthday.map(lambda x:pd.to_datetime('today').year-x.year))
df

       player_api_id          player_name   birthday  height  weight  age
0             505942   Aaron Appindangoye 1992-02-29  182.88     187   33
1             155782      Aaron Cresswell 1989-12-15  170.18     146   36
2             162549          Aaron Doran 1991-05-13  170.18     163   34
3              30572        Aaron Galindo 1982-05-08  182.88     198   43
4              23780         Aaron Hughes 1979-11-08  182.88     154   46
...              ...                  ...        ...     ...     ...  ...
11055          26357       Zoumana Camara 1979-04-03  182.88     168   46
11056         111182         Zsolt Laczko 1986-12-18  182.88     176   39
11057          36491            Zsolt Low 1979-04-29  180.34     154   46
11058          35506  Zurab Khizanishvili 1981-10-06  185.42     172   44
11059          39902   Zvjezdan Misimovic 1982-06-05  180.34     176   43

[11060 rows x 6 columns]

       player_api_id          player_name   birthday  height  weight
0             505942   Aaron Appindangoye 1992-02-29  182.88     187
1             155782      Aaron Cresswell 1989-12-15  170.18     146
2             162549          Aaron Doran 1991-05-13  170.18     163
3              30572        Aaron Galindo 1982-05-08  182.88     198
4              23780         Aaron Hughes 1979-11-08  182.88     154
...              ...                  ...        ...     ...     ...
11055          26357       Zoumana Camara 1979-04-03  182.88     168
11056         111182         Zsolt Laczko 1986-12-18  182.88     176
11057          36491            Zsolt Low 1979-04-29  180.34     154
11058          35506  Zurab Khizanishvili 1981-10-06  185.42     172
11059          39902   Zvjezdan Misimovic 1982-06-05  180.34     176

[11060 rows x 5 columns]

In [28]:
#时间索引的应用
df= pd.read_csv('../data/player.csv')#df
df.birthday=pd.to_datetime(df.birthday)
df.set_index('birthday',inplace=True)#设置出生日期列为索引列#df
# 利用时间索引实现数据查询
#利用索引获得1992-02-29出生日期的全部球员df.loc['1992-02-29']
#利用索引获得1992-02的全部球员
df.loc['1992-02']
# 查看92年2月到92年10月出生的球员
df = df.sort_index()
df.loc['1992-02':'1992-10']

            player_api_id            player_name  height  weight
birthday
1992-02-29         505942     Aaron Appindangoye  182.88     187
1992-02-16         278866  Aleksandar Stevanovic  175.26     143
1992-02-22         192504       Alexander Merkel  177.80     148
1992-02-20         265727        Alexandre Coeff  185.42     159
1992-02-01         420224             Ali Ghazal  187.96     185
...                   ...                    ...     ...     ...
1992-02-17         667964           Victor Braga  193.04     187
1992-02-26         274786         Vincent Bikana  185.42     187
1992-02-10         309052      Wojciech Lisowski  185.42     163
1992-02-15         280968          Yohan Croizet  177.80     183
1992-02-24         278863            Yunus Malli  177.80     159

[91 rows x 4 columns]

            player_api_id      player_name  height  weight
birthday
1992-02-01         420224       Ali Ghazal  187.96     185
1992-02-01         458810     Marco Franin  180.34     165
1992-02-01         229778     Lewis Horner  180.34     165
1992-02-02         571623    Unai Bustinza  175.26     168
1992-02-02         266280    Christ Mbondi  180.34     165
...                   ...              ...     ...     ...
1992-10-28         276734    Patrick Bauer  193.04     194
1992-10-29         160367      Ryan Scully  185.42     168
1992-10-31         460004    Dario Melnjak  177.80     161
1992-10-31         277821    Ayanda Patosi  175.26     148
1992-10-31         299411  Mario Sampirisi  187.96     183

[487 rows x 4 columns]