In [6]:
import numpy as np
import pandas as pd
df=pd.DataFrame([[1,2,3],[4,5,6]],columns=['id','x','y'])
df
df.set_index('id')
df.set_index('id',inplace=True)
df

   id  x  y
0   1  2  3
1   4  5  6

    x  y
id
1   2  3
4   5  6

    x  y
id
1   2  3
4   5  6

In [17]:
df=pd.DataFrame([[1,2,3],[4,5,6]],columns=['id','x','y'])
df
df.set_index(['id','x'],inplace=True)
df
df.reset_index(inplace=True)
df
df.set_index(['id','x'],inplace=True)
df
df.reset_index(level='id',inplace=True)
df
df.reset_index(level='x',inplace=True,drop=True)
df

   id  x  y
0   1  2  3
1   4  5  6

      y
id x
1  2  3
4  5  6

   id  x  y
0   1  2  3
1   4  5  6

      y
id x
1  2  3
4  5  6

   id  y
x
2   1  3
5   4  6

   id  y
0   1  3
1   4  6

In [ ]:
#高维索引的操作
np.random.seed(0)
df = pd.DataFrame(np.random.randint(0,20,(4,4)),
                  index=[['上半年','上半年','下半年','下半年'],['A组','B组','A组','B组']],
                  columns=[['一区','一区','二区','二区'],['苹果','橘子','苹果','橘子']])
df
# 列操作:df[高维索引，低维索引]
# 获得一区的数据
df['一区']

        一区     二区
        苹果  橘子 苹果  橘子
上半年 A组  12  15  0   3
    B组   3   7  9  19
下半年 A组  18   4  6  12
    B组   1   6  7  14

        苹果  橘子
上半年 A组  12  15
    B组   3   7
下半年 A组  18   4
    B组   1   6

上半年  A组    15
     B组     7
下半年  A组     4
     B组     6
Name: (一区, 橘子), dtype: int32

    一区     二区
    苹果  橘子 苹果  橘子
A组  12  15  0   3
B组   3   7  9  19

一区  苹果    12
    橘子    15
二区  苹果     0
    橘子     3
Name: (上半年, A组), dtype: int32

        一区     二区
        苹果  橘子 苹果  橘子
上半年 A组  12  15  0   3
    B组   3   7  9  19
下半年 A组  18   4  6  12
    B组   1   6  7  14

        一区     二区
        苹果  橘子 苹果  橘子
上半年 A组  12  15  0   3
    B组   3   7  9  19

        一区     二区
        苹果  橘子 苹果  橘子
上半年 A组  12  15  0   3
    B组   3   7  9  19
下半年 A组  18   4  6  12
    B组   1   6  7  14

In [ ]:
df = pd.read_csv('../data/player.csv', index_col=0)
df = df.assign(height_class=np.select([
    df.height >= 185,
    (df.height >= 165) & (df.height < 185)
], [2, 1], 0))
df.set_index('height_class', append=True, inplace=True)
#这个或
df = df.reset_index('player_api_id')
df.set_index('player_api_id', append=True, inplace=True)
df

In [7]:
# 获得一区、橘子的数据
df['一区','橘子']

上半年  A组    15
     B组     7
下半年  A组     4
     B组     6
Name: (一区, 橘子), dtype: int32

In [8]:
#行操作:df.loc[高维索引，低维索引]
# 获得上半年数据
df.loc['上半年']

    一区     二区
    苹果  橘子 苹果  橘子
A组  12  15  0   3
B组   3   7  9  19

In [9]:
#获得上半年A组数据
df.loc['上半年','A组']

一区  苹果    12
    橘子    15
二区  苹果     0
    橘子     3
Name: (上半年, A组), dtype: int32

In [10]:
# 使用标签索引列表获得数据
df.loc[['上半年','下半年']]

        一区     二区
        苹果  橘子 苹果  橘子
上半年 A组  12  15  0   3
    B组   3   7  9  19
下半年 A组  18   4  6  12
    B组   1   6  7  14

In [11]:
# 使用布尔列表获取数据
df.loc[[True,True,False,False]]
# 使用切片获取数据
df.loc['上半年':'下半年']

        一区     二区
        苹果  橘子 苹果  橘子
上半年 A组  12  15  0   3
    B组   3   7  9  19

        一区     二区
        苹果  橘子 苹果  橘子
上半年 A组  12  15  0   3
    B组   3   7  9  19
下半年 A组  18   4  6  12
    B组   1   6  7  14

In [14]:
df.index.get_level_values(0)
df.index.get_level_values(1)

Index(['上半年', '上半年', '下半年', '下半年'], dtype='object')

Index(['A组', 'B组', 'A组', 'B组'], dtype='object')

In [ ]:
#获取主键xs()
df
# 使用xs函数获取level=1，key=“A组"的数据df.xs('A组'level=1)

# 使用xs函数获取level=0，key="上半年"的数据df.xs('上半年'level=0)