In [2]:
import pandas as pd
import numpy as np
np.random.randint(0,100,(5,5))
np.random.seed(0)

array([[75, 72, 49, 84,  6],
       [15, 70, 55, 81, 19],
       [70, 41, 13, 55, 82],
       [34, 42,  5, 49, 99],
       [31, 48, 28, 96, 42]])

In [ ]:
df=pd.DataFrame(    (np.random.randint(0,20,(4,4))),
                index=[['上半年','上半年','下半年','下半年'],['A组','B组','A组','B组']],
                columns=[['一区','一区','二区','二区'],['苹果','橘子','苹果','橘子']]
                )
df

        一区      二区
        苹果  橘子  苹果  橘子
上半年 A组  18   0  14   3
    B组  12  10  11   4
下半年 A组   6   4  15   3
    B组  12   4   8  14

In [9]:
df=pd.read_csv('../data/player.csv',index_col=0)
df

                       player_name             birthday  height  weight
player_api_id
505942          Aaron Appindangoye  1992-02-29 00:00:00  182.88     187
155782             Aaron Cresswell  1989-12-15 00:00:00  170.18     146
162549                 Aaron Doran  1991-05-13 00:00:00  170.18     163
30572                Aaron Galindo  1982-05-08 00:00:00  182.88     198
23780                 Aaron Hughes  1979-11-08 00:00:00  182.88     154
...                            ...                  ...     ...     ...
26357               Zoumana Camara  1979-04-03 00:00:00  182.88     168
111182                Zsolt Laczko  1986-12-18 00:00:00  182.88     176
36491                    Zsolt Low  1979-04-29 00:00:00  180.34     154
35506          Zurab Khizanishvili  1981-10-06 00:00:00  185.42     172
39902           Zvjezdan Misimovic  1982-06-05 00:00:00  180.34     176

[11060 rows x 4 columns]

In [10]:
df=df.assign(height_class=np.select([df.height>=185,df.height>=165],[2,1],0))
df

,player_name,birthday,height,weight,height_class
player_api_id,,,,,
505942,Aaron Appindangoye,1992-02-29 00:00:00,182.88,187,1
155782,Aaron Cresswell,1989-12-15 00:00:00,170.18,146,1
162549,Aaron Doran,1991-05-13 00:00:00,170.18,163,1
30572,Aaron Galindo,1982-05-08 00:00:00,182.88,198,1
23780,Aaron Hughes,1979-11-08 00:00:00,182.88,154,1
...,...,...,...,...,...
26357,Zoumana Camara,1979-04-03 00:00:00,182.88,168,1
111182,Zsolt Laczko,1986-12-18 00:00:00,182.88,176,1
36491,Zsolt Low,1979-04-29 00:00:00,180.34,154,1
35506,Zurab Khizanishvili,1981-10-06 00:00:00,185.42,172,2
39902,Zvjezdan Misimovic,1982-06-05 00:00:00,180.34,176,1

In [11]:
df.set_index('height_class',append=True,inplace=True)
df

,,player_name,birthday,height,weight
player_api_id,height_class,,,,
505942,1,Aaron Appindangoye,1992-02-29 00:00:00,182.88,187
155782,1,Aaron Cresswell,1989-12-15 00:00:00,170.18,146
162549,1,Aaron Doran,1991-05-13 00:00:00,170.18,163
30572,1,Aaron Galindo,1982-05-08 00:00:00,182.88,198
23780,1,Aaron Hughes,1979-11-08 00:00:00,182.88,154
...,...,...,...,...,...
26357,1,Zoumana Camara,1979-04-03 00:00:00,182.88,168
111182,1,Zsolt Laczko,1986-12-18 00:00:00,182.88,176
36491,1,Zsolt Low,1979-04-29 00:00:00,180.34,154
35506,2,Zurab Khizanishvili,1981-10-06 00:00:00,185.42,172
39902,1,Zvjezdan Misimovic,1982-06-05 00:00:00,180.34,176

In [12]:
df.reset_index('player_api_id',inplace=True)
df

,player_api_id,player_name,birthday,height,weight
height_class,,,,,
1,505942,Aaron Appindangoye,1992-02-29 00:00:00,182.88,187
1,155782,Aaron Cresswell,1989-12-15 00:00:00,170.18,146
1,162549,Aaron Doran,1991-05-13 00:00:00,170.18,163
1,30572,Aaron Galindo,1982-05-08 00:00:00,182.88,198
1,23780,Aaron Hughes,1979-11-08 00:00:00,182.88,154
...,...,...,...,...,...
1,26357,Zoumana Camara,1979-04-03 00:00:00,182.88,168
1,111182,Zsolt Laczko,1986-12-18 00:00:00,182.88,176
1,36491,Zsolt Low,1979-04-29 00:00:00,180.34,154
2,35506,Zurab Khizanishvili,1981-10-06 00:00:00,185.42,172
1,39902,Zvjezdan Misimovic,1982-06-05 00:00:00,180.34,176

In [13]:
df.set_index('player_api_id',append=True,inplace=True)
df

                                    player_name             birthday  height  \
height_class player_api_id
1            505942          Aaron Appindangoye  1992-02-29 00:00:00  182.88
             155782             Aaron Cresswell  1989-12-15 00:00:00  170.18
             162549                 Aaron Doran  1991-05-13 00:00:00  170.18
             30572                Aaron Galindo  1982-05-08 00:00:00  182.88
             23780                 Aaron Hughes  1979-11-08 00:00:00  182.88
...                                         ...                  ...     ...
             26357               Zoumana Camara  1979-04-03 00:00:00  182.88
             111182                Zsolt Laczko  1986-12-18 00:00:00  182.88
             36491                    Zsolt Low  1979-04-29 00:00:00  180.34
2            35506          Zurab Khizanishvili  1981-10-06 00:00:00  185.42
1            39902           Zvjezdan Misimovic  1982-06-05 00:00:00  180.34

                            weight
height_class player_api_id
1            505942            187
             155782            146
             162549            163
             30572             198
             23780             154
...                            ...
             26357             168
             111182            176
             36491             154
2            35506             172
1            39902             176

[11060 rows x 4 columns]