In [26]:
import pandas as pd
import numpy as np

np.random.seed(0)

df=pd.DataFrame(    (np.random.randint(0,20,(4,4))),
                index=[['上半年','上半年','下半年','下半年'],['A组','B组','A组','B组']],
                columns=[['一区','一区','二区','二区'],['苹果','橘子','苹果','橘子']]
                )
df

        一区     二区
        苹果  橘子 苹果  橘子
上半年 A组  12  15  0   3
    B组   3   7  9  19
下半年 A组  18   4  6  12
    B组   1   6  7  14

In [ ]:
#列操作
df['一区']
df['一区','橘子']

        苹果  橘子
上半年 A组  12  15
    B组   3   7
下半年 A组  18   4
    B组   1   6

上半年  A组    15
     B组     7
下半年  A组     4
     B组     6
Name: (一区, 橘子), dtype: int32

In [10]:
#行操作
df.loc['上半年']
df.loc['上半年','A组']
df.loc[['上半年','下半年']]

    一区     二区
    苹果  橘子 苹果  橘子
A组  12  15  0   3
B组   3   7  9  19

一区  苹果    12
    橘子    15
二区  苹果     0
    橘子     3
Name: (上半年, A组), dtype: int32

        一区     二区
        苹果  橘子 苹果  橘子
上半年 A组  12  15  0   3
    B组   3   7  9  19
下半年 A组  18   4  6  12
    B组   1   6  7  14

In [11]:
df.swaplevel()

        一区     二区
        苹果  橘子 苹果  橘子
A组 上半年  12  15  0   3
B组 上半年   3   7  9  19
A组 下半年  18   4  6  12
B组 下半年   1   6  7  14

In [18]:
df.sort_index()#默认最外层
df.sort_index(level=1)#按内层索引排序
df.sort_index(axis=1)

     A  B
x  1.0  3
y  NaN  4

     A  B
x  1.0  3
y  NaN  4

     A  B
x  1.0  3
y  NaN  4

In [ ]:
df.stack()

In [20]:
#索引d堆叠
import pandas as pd
import numpy as np

df = pd.DataFrame({
    'A': [1, np.nan],
    'B': [3, 4]
}, index=['x', 'y'])

print(df)
df.stack()
df.stack(dropna=False)

     A  B
x  1.0  3
y  NaN  4

x  A    1.0
   B    3.0
y  B    4.0
dtype: float64

C:\Users\Flour\AppData\Local\Temp\ipykernel_38024\2353179814.py:12: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  df.stack(dropna=False)

x  A    1.0
   B    3.0
y  A    NaN
   B    4.0
dtype: float64

In [22]:
df.unstack()

     一区           二区
     苹果     橘子    苹果     橘子
     A组 B组  A组 B组 A组 B组  A组  B组
上半年  12  3  15  7  0  9   3  19
下半年  18  1   4  6  6  7  12  14

In [25]:
import pandas as pd

# 多层索引
index = pd.MultiIndex.from_tuples([('A', 1), ('A', 2), ('B', 1)], names=['group', 'id'])
data = pd.DataFrame({'value':[10, 20, 30]}, index=index)
print(data)
df_unstacked = data.unstack(level=-1)
print(df_unstacked)
df_unstacked = data.unstack(level=-1, fill_value=0)
print(df_unstacked)

          value
group id
A     1      10
      2      20
B     1      30
      value
id        1     2
group
A      10.0  20.0
B      30.0   NaN
      value
id        1   2
group
A        10  20
B        30   0

In [32]:
# 获取主键
import pandas as pd
import numpy as np

np.random.seed(0)

df=pd.DataFrame(    (np.random.randint(0,20,(4,4))),
                index=[['上半年','上半年','下半年','下半年'],['A组','B组','A组','B组']],
                columns=[['一区','一区','二区','二区'],['苹果','橘子','苹果','橘子']]
                )
df
df.xs('A组',level=1)
df.xs('一区',axis=1)
df.xs('一区',axis=1,drop_level=False)

        一区     二区
        苹果  橘子 苹果  橘子
上半年 A组  12  15  0   3
    B组   3   7  9  19
下半年 A组  18   4  6  12
    B组   1   6  7  14

     一区     二区
     苹果  橘子 苹果  橘子
上半年  12  15  0   3
下半年  18   4  6  12

        苹果  橘子
上半年 A组  12  15
    B组   3   7
下半年 A组  18   4
    B组   1   6

        一区
        苹果  橘子
上半年 A组  12  15
    B组   3   7
下半年 A组  18   4
    B组   1   6

In [33]:
df.index.get_level_values(level=0)

Index(['上半年', '上半年', '下半年', '下半年'], dtype='object')