In [ ]:
#df创建
import pandas as pd
import numpy as np

#1 二维列表创建
d=[
    [1,'john',18,'male','beijing'],
    [2,'susan',19,'female','shanghai'],
    [3,'gump',20,'male','newyork']
]
pd.DataFrame(data=d,index=[1,2,3],columns=['id','name','age','gender','adress'])

   id   name  age  gender    adress
1   1   john   18    male   beijing
2   2  susan   19  female  shanghai
3   3   gump   20    male   newyork

In [ ]:
#2 字典创建
dic1={
    1:[1,'john',18,'male','beijing'],
    2:[2,'susan',19,'female','shanghai'],
    3:[3,'gump',20,'male','newyork']
}
pd.DataFrame(dic1,index=['id','name','age','gender','adress']).T

  id   name age  gender    adress
1  1   john  18    male   beijing
2  2  susan  19  female  shanghai
3  3   gump  20    male   newyork

In [22]:
# 3 Series创建
name=pd.Series(['john','susan','gump'])
name
age=pd.Series([18,19,20])
age
pd.DataFrame([name,age]).T

0     john
1    susan
2     gump
dtype: object

0    18
1    19
2    20
dtype: int64

       0   1
0   john  18
1  susan  19
2   gump  20

In [26]:
# 4 to_frame创建
name.to_frame()

       0
0   john
1  susan
2   gump