In [1]:
import pandas as pd 
import numpy as np
df=pd.read_csv('../data/player.csv')
df

       player_api_id          player_name             birthday  height  weight
0             505942   Aaron Appindangoye  1992-02-29 00:00:00  182.88     187
1             155782      Aaron Cresswell  1989-12-15 00:00:00  170.18     146
2             162549          Aaron Doran  1991-05-13 00:00:00  170.18     163
3              30572        Aaron Galindo  1982-05-08 00:00:00  182.88     198
4              23780         Aaron Hughes  1979-11-08 00:00:00  182.88     154
...              ...                  ...                  ...     ...     ...
11055          26357       Zoumana Camara  1979-04-03 00:00:00  182.88     168
11056         111182         Zsolt Laczko  1986-12-18 00:00:00  182.88     176
11057          36491            Zsolt Low  1979-04-29 00:00:00  180.34     154
11058          35506  Zurab Khizanishvili  1981-10-06 00:00:00  185.42     172
11059          39902   Zvjezdan Misimovic  1982-06-05 00:00:00  180.34     176

[11060 rows x 5 columns]

In [2]:
df=pd.read_csv('../data/player.csv',index_col=0,usecols=[0,1,2])
df

                       player_name             birthday
player_api_id
505942          Aaron Appindangoye  1992-02-29 00:00:00
155782             Aaron Cresswell  1989-12-15 00:00:00
162549                 Aaron Doran  1991-05-13 00:00:00
30572                Aaron Galindo  1982-05-08 00:00:00
23780                 Aaron Hughes  1979-11-08 00:00:00
...                            ...                  ...
26357               Zoumana Camara  1979-04-03 00:00:00
111182                Zsolt Laczko  1986-12-18 00:00:00
36491                    Zsolt Low  1979-04-29 00:00:00
35506          Zurab Khizanishvili  1981-10-06 00:00:00
39902           Zvjezdan Misimovic  1982-06-05 00:00:00

[11060 rows x 2 columns]

In [3]:
df=pd.read_excel('../data/player.xlsx')
df

       player_api_id        player_name            birthday  height  weight
0                 -2           可怜的姆巴佩2号 2009-01-01 09:27:21     NaN     NaN
1                 -1           可怜的姆巴佩1号 2009-01-01 09:26:47     NaN     NaN
2               2625  Patryk Rachwal,18 1981-01-27 00:00:00  175.26   154.0
3               2752        Diego Mainz 1982-12-29 00:00:00  187.96   174.0
4               2768        Jose Dorado 1982-07-10 00:00:00  180.34   154.0
...              ...                ...                 ...     ...     ...
11056         743720     Charles Pickel 1997-05-15 00:00:00  185.42   176.0
11057         744907        Greg Taylor 1997-11-05 00:00:00  172.72   137.0
11058         746419   Francisco Afonso 1997-04-24 00:00:00  175.26   152.0
11059         748432     Fynn Arkenberg 1996-03-04 00:00:00  187.96   176.0
11060         750435     Rees Greenwood 1996-01-20 00:00:00  172.72   150.0

[11061 rows x 5 columns]

In [4]:
df=pd.read_excel('../data/player.xlsx',index_col=0,usecols=[1,2])
df

                             birthday
player_name
可怜的姆巴佩2号          2009-01-01 09:27:21
可怜的姆巴佩1号          2009-01-01 09:26:47
Patryk Rachwal,18 1981-01-27 00:00:00
Diego Mainz       1982-12-29 00:00:00
Jose Dorado       1982-07-10 00:00:00
...                               ...
Charles Pickel    1997-05-15 00:00:00
Greg Taylor       1997-11-05 00:00:00
Francisco Afonso  1997-04-24 00:00:00
Fynn Arkenberg    1996-03-04 00:00:00
Rees Greenwood    1996-01-20 00:00:00

[11061 rows x 1 columns]

In [7]:
df.to_excel('player2.xlsx')

In [10]:
df.to_excel('player2.xls',engine="xlwt")

ValueError: No Excel writer 'xlwt'