In [15]:
import pandas as pd
import numpy as np
#1 类型属性
df=pd.read_csv('../data/player.csv')
df.dtypes
df

player_api_id      int64
player_name       object
birthday          object
height           float64
weight             int64
dtype: object

       player_api_id          player_name             birthday  height  weight
0             505942   Aaron Appindangoye  1992-02-29 00:00:00  182.88     187
1             155782      Aaron Cresswell  1989-12-15 00:00:00  170.18     146
2             162549          Aaron Doran  1991-05-13 00:00:00  170.18     163
3              30572        Aaron Galindo  1982-05-08 00:00:00  182.88     198
4              23780         Aaron Hughes  1979-11-08 00:00:00  182.88     154
...              ...                  ...                  ...     ...     ...
11055          26357       Zoumana Camara  1979-04-03 00:00:00  182.88     168
11056         111182         Zsolt Laczko  1986-12-18 00:00:00  182.88     176
11057          36491            Zsolt Low  1979-04-29 00:00:00  180.34     154
11058          35506  Zurab Khizanishvili  1981-10-06 00:00:00  185.42     172
11059          39902   Zvjezdan Misimovic  1982-06-05 00:00:00  180.34     176

[11060 rows x 5 columns]

In [ ]:
#2
df.astype({'weight':'float64'})

       player_api_id          player_name             birthday  height  weight
0             505942   Aaron Appindangoye  1992-02-29 00:00:00  182.88   187.0
1             155782      Aaron Cresswell  1989-12-15 00:00:00  170.18   146.0
2             162549          Aaron Doran  1991-05-13 00:00:00  170.18   163.0
3              30572        Aaron Galindo  1982-05-08 00:00:00  182.88   198.0
4              23780         Aaron Hughes  1979-11-08 00:00:00  182.88   154.0
...              ...                  ...                  ...     ...     ...
11055          26357       Zoumana Camara  1979-04-03 00:00:00  182.88   168.0
11056         111182         Zsolt Laczko  1986-12-18 00:00:00  182.88   176.0
11057          36491            Zsolt Low  1979-04-29 00:00:00  180.34   154.0
11058          35506  Zurab Khizanishvili  1981-10-06 00:00:00  185.42   172.0
11059          39902   Zvjezdan Misimovic  1982-06-05 00:00:00  180.34   176.0

[11060 rows x 5 columns]

In [14]:
# 3
df.index
df.columns

RangeIndex(start=1, stop=11061, step=1)

Index([1, 2, 3, 4, 5], dtype='int64')

In [ ]:
# 4
# df.index=range(1,len(df)+1)
# df
# df.columns=[1,2,3,4,5]
# df

            1                    2                    3       4    5
1      505942   Aaron Appindangoye  1992-02-29 00:00:00  182.88  187
2      155782      Aaron Cresswell  1989-12-15 00:00:00  170.18  146
3      162549          Aaron Doran  1991-05-13 00:00:00  170.18  163
4       30572        Aaron Galindo  1982-05-08 00:00:00  182.88  198
5       23780         Aaron Hughes  1979-11-08 00:00:00  182.88  154
...       ...                  ...                  ...     ...  ...
11056   26357       Zoumana Camara  1979-04-03 00:00:00  182.88  168
11057  111182         Zsolt Laczko  1986-12-18 00:00:00  182.88  176
11058   36491            Zsolt Low  1979-04-29 00:00:00  180.34  154
11059   35506  Zurab Khizanishvili  1981-10-06 00:00:00  185.42  172
11060   39902   Zvjezdan Misimovic  1982-06-05 00:00:00  180.34  176

[11060 rows x 5 columns]

            1                    2                    3       4    5
1      505942   Aaron Appindangoye  1992-02-29 00:00:00  182.88  187
2      155782      Aaron Cresswell  1989-12-15 00:00:00  170.18  146
3      162549          Aaron Doran  1991-05-13 00:00:00  170.18  163
4       30572        Aaron Galindo  1982-05-08 00:00:00  182.88  198
5       23780         Aaron Hughes  1979-11-08 00:00:00  182.88  154
...       ...                  ...                  ...     ...  ...
11056   26357       Zoumana Camara  1979-04-03 00:00:00  182.88  168
11057  111182         Zsolt Laczko  1986-12-18 00:00:00  182.88  176
11058   36491            Zsolt Low  1979-04-29 00:00:00  180.34  154
11059   35506  Zurab Khizanishvili  1981-10-06 00:00:00  185.42  172
11060   39902   Zvjezdan Misimovic  1982-06-05 00:00:00  180.34  176

[11060 rows x 5 columns]

In [22]:
df=df.rename(columns={'birthday':1})
df=df.rename(index={1:11})
df

       player_api_id          player_name                    1  height  weight
0             505942   Aaron Appindangoye  1992-02-29 00:00:00  182.88     187
11            155782      Aaron Cresswell  1989-12-15 00:00:00  170.18     146
2             162549          Aaron Doran  1991-05-13 00:00:00  170.18     163
3              30572        Aaron Galindo  1982-05-08 00:00:00  182.88     198
4              23780         Aaron Hughes  1979-11-08 00:00:00  182.88     154
...              ...                  ...                  ...     ...     ...
11055          26357       Zoumana Camara  1979-04-03 00:00:00  182.88     168
11056         111182         Zsolt Laczko  1986-12-18 00:00:00  182.88     176
11057          36491            Zsolt Low  1979-04-29 00:00:00  180.34     154
11058          35506  Zurab Khizanishvili  1981-10-06 00:00:00  185.42     172
11059          39902   Zvjezdan Misimovic  1982-06-05 00:00:00  180.34     176

[11060 rows x 5 columns]

In [23]:
#5 
df.shape

(11060, 5)