In [1]:
import pandas as pd
import numpy as np
#生成数据
df=pd.DataFrame([
[2,5,9],
[2,10,9],
[1,2,6],
[1,5,6],
[1,2,3],
[2,5,8]
],columns=['a','b','c']) 
df
df.groupby(['a','b'])

   a   b  c
0  2   5  9
1  2  10  9
2  1   2  6
3  1   5  6
4  1   2  3
5  2   5  8

In [2]:
ga=df.groupby('a')
for i in ga:
    i

(1,
    a  b  c
 2  1  2  6
 3  1  5  6
 4  1  2  3)

(2,
    a   b  c
 0  2   5  9
 1  2  10  9
 5  2   5  8)

In [2]:
gab=df.groupby(['a','b'])
for i in gab:
    print(i)

((1, 2),    a  b  c
2  1  2  6
4  1  2  3)
((1, 5),    a  b  c
3  1  5  6)
((2, 5),    a  b  c
0  2  5  9
5  2  5  8)
((2, 10),    a   b  c
1  2  10  9)

In [4]:
#创建高维索引数据
df = pd.DataFrame([
[1,2],[3,4],[5,6],[7,8]
],index=[['a','a','b','b'],['c','d','c','d']])
df
#设置level=1实现按照第2层索引分组
g1=df.groupby(level=1)
#使用for循环选代输出分组结果
for i in g1:
    print(i)

     0  1
a c  1  2
  d  3  4
b c  5  6
  d  7  8

('c',      0  1
a c  1  2
b c  5  6)
('d',      0  1
a d  3  4
b d  7  8)

In [ ]:
#分组后的属性groups
df
df.groupby(level=1).groups

     0  1
a c  1  2
  d  3  4
b c  5  6
  d  7  8

{'c': [('a', 'c'), ('b', 'c')], 'd': [('a', 'd'), ('b', 'd')]}

In [5]:
#分组后的函数df
df
df.groupby(level=1).get_group('c')

     0  1
a c  1  2
  d  3  4
b c  5  6
  d  7  8

     0  1
a c  1  2
b c  5  6

In [7]:
#分组后的函数first（)每组的第一条数据last（O每组的最后一条数据
df
df.groupby(level=1).first()
df.groupby(level=1).last()

     0  1
a c  1  2
  d  3  4
b c  5  6
  d  7  8

   0  1
c  1  2
d  3  4

   0  1
c  5  6
d  7  8

In [8]:

#分组后的函数 size每组数据的个数
df
df.groupby(level=1).size()

     0  1
a c  1  2
  d  3  4
b c  5  6
  d  7  8

c    2
d    2
dtype: int64

In [7]:
#分组后的函数 nunique() 对每个分组的 每一列 统计唯一值数量。
df = pd.DataFrame([
[1,3],[3,4],[1,6],[7,8]
],index=[['a','a','b','b'],['c','d','c','d']])
df
df.groupby(level=1).nunique()

     0  1
a c  1  3
  d  3  4
b c  1  6
  d  7  8

   0  1
c  1  2
d  2  2

In [11]:
#分组后的函数value_counts（） 唯一值的统计
df = pd.DataFrame([
[1,2],[3,4],[1,2],[7,8]
],index=[['a','a','b','b'],['c','d','c','d']])
df
df.groupby(level=1).value_counts()

     0  1
a c  1  2
  d  3  4
b c  1  2
  d  7  8

   0  1
c  1  2    2
d  3  4    1
   7  8    1
Name: count, dtype: int64

In [9]:
#高维索引I下的分组操作# 创建DataFrame
df=pd.DataFrame({
'a':[1,1,1,2,2,2],
'b':[2,5,2,10,5,5],'c' :[3,6,6,9,9,8]
})
#df
#设置高维索引
df.set_index(['a','b'],inplace=True)
df
#对比具有高维索引|的情况与没有高维索引情况下的分组操作
#有高维索引
df.c.groupby(level=0).groups#没有高维索引
df.c.groupby(level=1).groups#没有高维索引
df.reset_index('b',inplace=True)
df
df.c.groupby(level=0).groups

      c
a b
1 2   3
  5   6
  2   6
2 10  9
  5   9
  5   8

{1: [(1, 2), (1, 5), (1, 2)], 2: [(2, 10), (2, 5), (2, 5)]}

{2: [(1, 2), (1, 2)], 5: [(1, 5), (2, 5), (2, 5)], 10: [(2, 10)]}

    b  c
a
1   2  3
1   5  6
1   2  6
2  10  9
2   5  9
2   5  8

{1: [1, 1, 1], 2: [2, 2, 2]}

In [11]:
import pandas as pd
import numpy as np

# 创建示例数据
data = {
    'Year': [2023, 2023, 2023, 2023, 2024, 2024, 2024, 2024],
    'Quarter': ['Q1', 'Q1', 'Q2', 'Q2', 'Q1', 'Q1', 'Q2', 'Q2'],
    'Region': ['North', 'South', 'North', 'South', 'North', 'South', 'North', 'South'],
    'Sales': [100, 150, 120, 180, 130, 160, 140, 190],
    'Profit': [20, 30, 25, 35, 28, 32, 30, 38]
}

df = pd.DataFrame(data)
print("原始数据:")
print(df)
# 设置高维索引（Year, Quarter, Region）
df_multiindex = df.set_index(['Year', 'Quarter', 'Region'])
print("\n设置高维索引后的DataFrame:")
print(df_multiindex)

原始数据:
   Year Quarter Region  Sales  Profit
0  2023      Q1  North    100      20
1  2023      Q1  South    150      30
2  2023      Q2  North    120      25
3  2023      Q2  South    180      35
4  2024      Q1  North    130      28
5  2024      Q1  South    160      32
6  2024      Q2  North    140      30
7  2024      Q2  South    190      38

设置高维索引后的DataFrame:
                     Sales  Profit
Year Quarter Region
2023 Q1      North     100      20
             South     150      30
     Q2      North     120      25
             South     180      35
2024 Q1      North     130      28
             South     160      32
     Q2      North     140      30
             South     190      38

In [12]:
# 使用高维索引分组 - 高效方式
sales_by_year = df_multiindex.Sales.groupby('Year').sum()
print("\n按年份分组销售额（高维索引）:")
print(sales_by_year)

按年份分组销售额（高维索引）:
Year
2023    550
2024    620
Name: Sales, dtype: int64

In [13]:
# 传统分组方式（无高维索引）
traditional_grouping = df.groupby('Year')['Sales'].sum()
print("\n传统分组方式结果:")
print(traditional_grouping)

# 验证结果是否一致
print(f"\n结果是否一致: {sales_by_year.equals(traditional_grouping)}")

传统分组方式结果:
Year
2023    550
2024    620
Name: Sales, dtype: int64

结果是否一致: True