In [1]:
import pandas as pd
import numpy as np
#生成数据
df=pd.DataFrame([
[2,5,9],
[2,10,9],
[1,2,6],
[1,5,6],
[1,2,3],
[2,5,8]
],columns=['a','b','c']) 
df
df.groupby(['a','b'])

   a   b  c
0  2   5  9
1  2  10  9
2  1   2  6
3  1   5  6
4  1   2  3
5  2   5  8

In [2]:
gab=df.groupby(['a','b'])
for i in gab:
    print(i)

((1, 2),    a  b  c
2  1  2  6
4  1  2  3)
((1, 5),    a  b  c
3  1  5  6)
((2, 5),    a  b  c
0  2  5  9
5  2  5  8)
((2, 10),    a   b  c
1  2  10  9)

In [ ]:
#创建高维索引数据
df = pd.DataFrame([
[1,2],[3,4],[5,6],[7,8]
],index=[['a','a','b','b'],['c','d','c','d']])
df
#设置level=1实现按照第2层索引分组
g1=df.groupby(level=1)
#使用for循环选代输出分组结果
for i in g1:
    print(i)

     0  1
a c  1  2
  d  3  4
b c  5  6
  d  7  8

('c',      0  1
a c  1  2
b c  5  6)
('d',      0  1
a d  3  4
b d  7  8)

In [5]:
#分组后的属性groupsdf
df
df.groupby(level=1).groups

     0  1
a c  1  2
  d  3  4
b c  5  6
  d  7  8

{'c': [('a', 'c'), ('b', 'c')], 'd': [('a', 'd'), ('b', 'd')]}

In [6]:
#分组后的函数df
df
df.groupby(level=1).get_group('c')

     0  1
a c  1  2
  d  3  4
b c  5  6
  d  7  8

     0  1
a c  1  2
b c  5  6

In [7]:
#分组后的函数first（)每组的第一条数据last（O每组的最后一条数据
df
df.groupby(level=1).first()
df.groupby(level=1).last()

     0  1
a c  1  2
  d  3  4
b c  5  6
  d  7  8

   0  1
c  1  2
d  3  4

   0  1
c  5  6
d  7  8

In [8]:

#分组后的函数 size每组数据的个数
df
df.groupby(level=1).size()

     0  1
a c  1  2
  d  3  4
b c  5  6
  d  7  8

c    2
d    2
dtype: int64

In [ ]:
#分组后的函数 nunique() 对每个分组的 每一列 统计唯一值数量。
df = pd.DataFrame([
[1,3],[3,4],[1,6],[7,8]
],index=[['a','a','b','b'],['c','d','c','d']])
df
df.groupby(level=1) .nunique()

     0  1
a c  1  3
  d  3  4
b c  1  6
  d  7  8

   0  1
c  1  2
d  2  2

In [11]:
#分组后的函数value_counts（） 唯一值的统计
df = pd.DataFrame([
[1,2],[3,4],[1,2],[7,8]
],index=[['a','a','b','b'],['c','d','c','d']])
df
df.groupby(level=1).value_counts()

     0  1
a c  1  2
  d  3  4
b c  1  2
  d  7  8

   0  1
c  1  2    2
d  3  4    1
   7  8    1
Name: count, dtype: int64

In [15]:
#高维索引I下的分组操作# 创建DataFrame
df=pd.DataFrame({
'a':[1,1,1,2,2,2],
'b':[2,5,2,10,5,5],'c' :[3,6,6,9,9,8]
})
#df
#设置高维索引
df.set_index(['a','b'],inplace=True)
df
#对比具有高维索引|的情况与没有高维索引情况下的分组操作
#有高维索引
df.c.groupby(level=0).groups#没有高维索引
df.reset_index('b',inplace=True)
df
df.c.groupby(level=0).groups

      c
a b
1 2   3
  5   6
  2   6
2 10  9
  5   9
  5   8

{1: [(1, 2), (1, 5), (1, 2)], 2: [(2, 10), (2, 5), (2, 5)]}

    b  c
a
1   2  3
1   5  6
1   2  6
2  10  9
2   5  9
2   5  8

{1: [1, 1, 1], 2: [2, 2, 2]}