In [1]:
import pandas as pd
import numpy as np
np.random.seed(0)
a=pd.DataFrame(np.random.randint(10,100,(20,4)),
               columns=['S0','S1','S2','S3'],
               )
a
a['I1']=[0,1]*10
a
a.set_index('I1',inplace=True)
a

    S0  S1  S2  S3
0   54  57  74  77
1   77  19  93  31
2   46  97  80  98
3   98  22  68  75
4   49  97  56  98
5   91  47  35  87
6   82  19  30  90
7   79  89  57  74
8   92  98  59  39
9   29  29  24  49
10  42  75  19  67
11  42  41  84  33
12  45  85  65  38
13  44  10  10  46
14  63  15  48  27
15  89  14  52  68
16  41  11  75  51
17  67  45  21  56
18  92  10  24  63
19  22  52  94  85

    S0  S1  S2  S3  I1
0   54  57  74  77   0
1   77  19  93  31   1
2   46  97  80  98   0
3   98  22  68  75   1
4   49  97  56  98   0
5   91  47  35  87   1
6   82  19  30  90   0
7   79  89  57  74   1
8   92  98  59  39   0
9   29  29  24  49   1
10  42  75  19  67   0
11  42  41  84  33   1
12  45  85  65  38   0
13  44  10  10  46   1
14  63  15  48  27   0
15  89  14  52  68   1
16  41  11  75  51   0
17  67  45  21  56   1
18  92  10  24  63   0
19  22  52  94  85   1

    S0  S1  S2  S3
I1
0   54  57  74  77
1   77  19  93  31
0   46  97  80  98
1   98  22  68  75
0   49  97  56  98
1   91  47  35  87
0   82  19  30  90
1   79  89  57  74
0   92  98  59  39
1   29  29  24  49
0   42  75  19  67
1   42  41  84  33
0   45  85  65  38
1   44  10  10  46
0   63  15  48  27
1   89  14  52  68
0   41  11  75  51
1   67  45  21  56
0   92  10  24  63
1   22  52  94  85

In [2]:
a.groupby(level=0).mean()

      S0    S1    S2    S3
I1
0   60.6  56.4  53.0  64.8
1   63.8  36.8  53.8  60.4

In [3]:
a.groupby(level=0).sum()
a.groupby(level=0).sum()['S1']
a.groupby(level=0)['S1'].sum()

     S0   S1   S2   S3
I1
0   606  564  530  648
1   638  368  538  604

I1
0    564
1    368
Name: S1, dtype: int32

I1
0    564
1    368
Name: S1, dtype: int32

In [4]:
a.reset_index(inplace=True)
a

    I1  S0  S1  S2  S3
0    0  54  57  74  77
1    1  77  19  93  31
2    0  46  97  80  98
3    1  98  22  68  75
4    0  49  97  56  98
5    1  91  47  35  87
6    0  82  19  30  90
7    1  79  89  57  74
8    0  92  98  59  39
9    1  29  29  24  49
10   0  42  75  19  67
11   1  42  41  84  33
12   0  45  85  65  38
13   1  44  10  10  46
14   0  63  15  48  27
15   1  89  14  52  68
16   0  41  11  75  51
17   1  67  45  21  56
18   0  92  10  24  63
19   1  22  52  94  85

In [5]:
a.groupby(by='I1').mean()

      S0    S1    S2    S3
I1
0   60.6  56.4  53.0  64.8
1   63.8  36.8  53.8  60.4

In [6]:
a.groupby(by='I1')['S1'].sum()

I1
0    564
1    368
Name: S1, dtype: int32

In [7]:
#滚动窗口聚合rolling()
a.groupby(by='I1').rolling(5).mean()
# 最小窗口为1
#min_periods=1()
a.groupby(by='I1').rolling(5,min_periods=1).mean().round(2)

         S0    S1    S2    S3
I1
0  0    NaN   NaN   NaN   NaN
   2    NaN   NaN   NaN   NaN
   4    NaN   NaN   NaN   NaN
   6    NaN   NaN   NaN   NaN
   8   64.6  73.6  59.8  80.4
   10  62.2  77.2  48.8  78.4
   12  62.0  74.8  45.8  66.4
   14  64.8  58.4  44.2  52.2
   16  56.6  56.8  53.2  44.4
   18  56.6  39.2  46.2  49.2
1  1    NaN   NaN   NaN   NaN
   3    NaN   NaN   NaN   NaN
   5    NaN   NaN   NaN   NaN
   7    NaN   NaN   NaN   NaN
   9   74.8  41.2  55.4  63.2
   11  67.8  45.6  53.6  63.6
   13  57.0  43.2  42.0  57.8
   15  56.6  36.6  45.4  54.0
   17  54.2  27.8  38.2  50.4
   19  52.8  32.4  52.2  57.6

          S0     S1     S2     S3
I1
0  0   54.00  57.00  74.00  77.00
   2   50.00  77.00  77.00  87.50
   4   49.67  83.67  70.00  91.00
   6   57.75  67.50  60.00  90.75
   8   64.60  73.60  59.80  80.40
   10  62.20  77.20  48.80  78.40
   12  62.00  74.80  45.80  66.40
   14  64.80  58.40  44.20  52.20
   16  56.60  56.80  53.20  44.40
   18  56.60  39.20  46.20  49.20
1  1   77.00  19.00  93.00  31.00
   3   87.50  20.50  80.50  53.00
   5   88.67  29.33  65.33  64.33
   7   86.25  44.25  63.25  66.75
   9   74.80  41.20  55.40  63.20
   11  67.80  45.60  53.60  63.60
   13  57.00  43.20  42.00  57.80
   15  56.60  36.60  45.40  54.00
   17  54.20  27.80  38.20  50.40
   19  52.80  32.40  52.20  57.60

In [8]:
a.reset_index(inplace=True)

In [9]:
b=a.groupby(by='I1').transform('mean').rename(columns={'S0':'S0_mean','S1':'S1_mean','S2':'S2_mean','S3':'S3_mean'})
b

a=a.merge(b,how='inner',)
a

    index  S0_mean  S1_mean  S2_mean  S3_mean
0     9.0     60.6     56.4     53.0     64.8
1    10.0     63.8     36.8     53.8     60.4
2     9.0     60.6     56.4     53.0     64.8
3    10.0     63.8     36.8     53.8     60.4
4     9.0     60.6     56.4     53.0     64.8
5    10.0     63.8     36.8     53.8     60.4
6     9.0     60.6     56.4     53.0     64.8
7    10.0     63.8     36.8     53.8     60.4
8     9.0     60.6     56.4     53.0     64.8
9    10.0     63.8     36.8     53.8     60.4
10    9.0     60.6     56.4     53.0     64.8
11   10.0     63.8     36.8     53.8     60.4
12    9.0     60.6     56.4     53.0     64.8
13   10.0     63.8     36.8     53.8     60.4
14    9.0     60.6     56.4     53.0     64.8
15   10.0     63.8     36.8     53.8     60.4
16    9.0     60.6     56.4     53.0     64.8
17   10.0     63.8     36.8     53.8     60.4
18    9.0     60.6     56.4     53.0     64.8
19   10.0     63.8     36.8     53.8     60.4

    index  I1  S0  S1  S2  S3  S0_mean  S1_mean  S2_mean  S3_mean
0       9   1  29  29  24  49     60.6     56.4     53.0     64.8
1       9   1  29  29  24  49     60.6     56.4     53.0     64.8
2       9   1  29  29  24  49     60.6     56.4     53.0     64.8
3       9   1  29  29  24  49     60.6     56.4     53.0     64.8
4       9   1  29  29  24  49     60.6     56.4     53.0     64.8
5       9   1  29  29  24  49     60.6     56.4     53.0     64.8
6       9   1  29  29  24  49     60.6     56.4     53.0     64.8
7       9   1  29  29  24  49     60.6     56.4     53.0     64.8
8       9   1  29  29  24  49     60.6     56.4     53.0     64.8
9       9   1  29  29  24  49     60.6     56.4     53.0     64.8
10     10   0  42  75  19  67     63.8     36.8     53.8     60.4
11     10   0  42  75  19  67     63.8     36.8     53.8     60.4
12     10   0  42  75  19  67     63.8     36.8     53.8     60.4
13     10   0  42  75  19  67     63.8     36.8     53.8     60.4
14     10   0  42  75  19  67     63.8     36.8     53.8     60.4
15     10   0  42  75  19  67     63.8     36.8     53.8     60.4
16     10   0  42  75  19  67     63.8     36.8     53.8     60.4
17     10   0  42  75  19  67     63.8     36.8     53.8     60.4
18     10   0  42  75  19  67     63.8     36.8     53.8     60.4
19     10   0  42  75  19  67     63.8     36.8     53.8     60.4

In [18]:
#apply
import pandas as pd
import numpy as np
#生成数据
df=pd.DataFrame([
[2,5,9],
[2,10,9],
[1,2,6],
[1,5,6],
[1,2,3],
[2,5,8]
],columns=['a','b','c']) 
df
df.groupby(['a']).mean()
df.groupby('a').mean()
df.groupby('a',group_keys=False).apply(lambda x:x-x.mean())
df.groupby('a',group_keys=False)['b'].apply(lambda x:x-x.mean())

   a   b  c
0  2   5  9
1  2  10  9
2  1   2  6
3  1   5  6
4  1   2  3
5  2   5  8

          b         c
a
1  3.000000  5.000000
2  6.666667  8.666667

          b         c
a
1  3.000000  5.000000
2  6.666667  8.666667

C:\Users\123\AppData\Local\Temp\ipykernel_16892\1915228521.py:16: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df.groupby('a',group_keys=False).apply(lambda x:x-x.mean())

     a         b         c
0  0.0 -1.666667  0.333333
1  0.0  3.333333  0.333333
2  0.0 -1.000000  1.000000
3  0.0  2.000000  1.000000
4  0.0 -1.000000 -2.000000
5  0.0 -1.666667 -0.666667

0   -1.666667
1    3.333333
2   -1.000000
3    2.000000
4   -1.000000
5   -1.666667
Name: b, dtype: float64

In [24]:
df.agg('mean')
df.agg(np.mean)
df.agg(['mean','max'])
df.agg([np.mean,np.max])
df.agg({'b':np.mean,'c':'max'})

a    1.500000
b    4.833333
c    6.833333
dtype: float64

C:\Users\123\AppData\Local\Temp\ipykernel_16892\3636169768.py:2: FutureWarning: The provided callable <function mean at 0x0000025B914ACFE0> is currently using DataFrame.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  df.agg(np.mean)

a    1.500000
b    4.833333
c    6.833333
dtype: float64

        a          b         c
mean  1.5   4.833333  6.833333
max   2.0  10.000000  9.000000

C:\Users\123\AppData\Local\Temp\ipykernel_16892\3636169768.py:4: FutureWarning: The provided callable <function mean at 0x0000025B914ACFE0> is currently using Series.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  df.agg([np.mean,np.max])
C:\Users\123\AppData\Local\Temp\ipykernel_16892\3636169768.py:4: FutureWarning: The provided callable <function max at 0x0000025B914AC5E0> is currently using Series.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  df.agg([np.mean,np.max])

        a          b         c
mean  1.5   4.833333  6.833333
max   2.0  10.000000  9.000000

C:\Users\123\AppData\Local\Temp\ipykernel_16892\3636169768.py:5: FutureWarning: The provided callable <function mean at 0x0000025B914ACFE0> is currently using Series.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  df.agg({'b':np.mean,'c':'max'})

b    4.833333
c    9.000000
dtype: float64