In [7]:
import pandas as pd
import numpy as np
df=pd.read_csv('..\data\player.csv')
df
#df.head(2)
# 分别为数据集设置高维索引
# weight_class:weight>170为1，否则为0
#height class:height>185为1，否则为
# 分别使用np.select和np.where完成
df['weight_class']=np.select([df['weight']>170],[1],0)
df['height_class']=np.where(df['height']>185,1,0)
df
df.set_index(['weight_class','height_class'],inplace=True)
df

       player_api_id          player_name             birthday  height  weight
0             505942   Aaron Appindangoye  1992-02-29 00:00:00  182.88     187
1             155782      Aaron Cresswell  1989-12-15 00:00:00  170.18     146
2             162549          Aaron Doran  1991-05-13 00:00:00  170.18     163
3              30572        Aaron Galindo  1982-05-08 00:00:00  182.88     198
4              23780         Aaron Hughes  1979-11-08 00:00:00  182.88     154
...              ...                  ...                  ...     ...     ...
11055          26357       Zoumana Camara  1979-04-03 00:00:00  182.88     168
11056         111182         Zsolt Laczko  1986-12-18 00:00:00  182.88     176
11057          36491            Zsolt Low  1979-04-29 00:00:00  180.34     154
11058          35506  Zurab Khizanishvili  1981-10-06 00:00:00  185.42     172
11059          39902   Zvjezdan Misimovic  1982-06-05 00:00:00  180.34     176

[11060 rows x 5 columns]

,player_api_id,player_name,birthday,height,weight,weight_class,height_class
0,505942,Aaron Appindangoye,1992-02-29 00:00:00,182.88,187,1,0
1,155782,Aaron Cresswell,1989-12-15 00:00:00,170.18,146,0,0
2,162549,Aaron Doran,1991-05-13 00:00:00,170.18,163,0,0
3,30572,Aaron Galindo,1982-05-08 00:00:00,182.88,198,1,0
4,23780,Aaron Hughes,1979-11-08 00:00:00,182.88,154,0,0
...,...,...,...,...,...,...,...
11055,26357,Zoumana Camara,1979-04-03 00:00:00,182.88,168,0,0
11056,111182,Zsolt Laczko,1986-12-18 00:00:00,182.88,176,1,0
11057,36491,Zsolt Low,1979-04-29 00:00:00,180.34,154,0,0
11058,35506,Zurab Khizanishvili,1981-10-06 00:00:00,185.42,172,1,1
11059,39902,Zvjezdan Misimovic,1982-06-05 00:00:00,180.34,176,1,0

                           player_api_id          player_name  \
weight_class height_class
1            0                    505942   Aaron Appindangoye
0            0                    155782      Aaron Cresswell
             0                    162549          Aaron Doran
1            0                     30572        Aaron Galindo
0            0                     23780         Aaron Hughes
...                                  ...                  ...
             0                     26357       Zoumana Camara
1            0                    111182         Zsolt Laczko
0            0                     36491            Zsolt Low
1            1                     35506  Zurab Khizanishvili
             0                     39902   Zvjezdan Misimovic

                                      birthday  height  weight
weight_class height_class
1            0             1992-02-29 00:00:00  182.88     187
0            0             1989-12-15 00:00:00  170.18     146
             0             1991-05-13 00:00:00  170.18     163
1            0             1982-05-08 00:00:00  182.88     198
0            0             1979-11-08 00:00:00  182.88     154
...                                        ...     ...     ...
             0             1979-04-03 00:00:00  182.88     168
1            0             1986-12-18 00:00:00  182.88     176
0            0             1979-04-29 00:00:00  180.34     154
1            1             1981-10-06 00:00:00  185.42     172
             0             1982-06-05 00:00:00  180.34     176

[11060 rows x 5 columns]

In [9]:
#分别按照身高分类、体重分类分组并实现对应分组平均值的聚合
df.groupby('height_class')['height'].mean()
df.groupby('weight_class')['weight'].mean()

height_class
0    178.148788
1    188.651430
Name: height, dtype: float64

weight_class
0    158.091753
1    182.271781
Name: weight, dtype: float64

In [10]:
# 按身高分类分组后，获取身高分类为0的数据
df.groupby('height_class').get_group(0)

                           player_api_id         player_name  \
weight_class height_class
1            0                    505942  Aaron Appindangoye
0            0                    155782     Aaron Cresswell
             0                    162549         Aaron Doran
1            0                     30572       Aaron Galindo
0            0                     23780        Aaron Hughes
...                                  ...                 ...
             0                    192132  Zouhaier Dhaouadhi
             0                     26357      Zoumana Camara
1            0                    111182        Zsolt Laczko
0            0                     36491           Zsolt Low
1            0                     39902  Zvjezdan Misimovic

                                      birthday  height  weight
weight_class height_class
1            0             1992-02-29 00:00:00  182.88     187
0            0             1989-12-15 00:00:00  170.18     146
             0             1991-05-13 00:00:00  170.18     163
1            0             1982-05-08 00:00:00  182.88     198
0            0             1979-11-08 00:00:00  182.88     154
...                                        ...     ...     ...
             0             1988-01-01 00:00:00  180.34     159
             0             1979-04-03 00:00:00  182.88     168
1            0             1986-12-18 00:00:00  182.88     176
0            0             1979-04-29 00:00:00  180.34     154
1            0             1982-06-05 00:00:00  180.34     176

[7144 rows x 5 columns]

In [11]:
#将数据按照身高分类分组，对分组结果的体重进行均值聚合
df.groupby('height_class')[['weight']].mean()

                  weight
height_class
0             161.599944
1             180.749745

In [12]:
# 将数据按照身高分类分组，实现每个球员的体重与组内均值的差
df.groupby('height_class', group_keys=True)[['weight']].apply(lambda x:x-x.mean())

                                           weight
height_class weight_class height_class
0            1            0             25.400056
             0            0            -15.599944
                          0              1.400056
             1            0             36.400056
             0            0             -7.599944
...                                           ...
1            1            1              2.250255
             0            1            -15.749745
             1            1             -1.749745
                          1             -8.749745
                          1             -8.749745

[11060 rows x 1 columns]

In [14]:
#实现按照球员出生年份分组，并对分组后的球员身高、体重实现平均值、计数聚合
df['year']=df.birthday.apply(lambda x:x[:4])
df.head(2)
df.groupby(by='year').agg({'height':'mean','weight':'mean','player_api_id':'count'}).rename(columns={'player_api_id':'人数'})

,,player_api_id,player_name,birthday,height,weight,year
weight_class,height_class,,,,,,
1,0,505942,Aaron Appindangoye,1992-02-29 00:00:00,182.88,187,1992
0,0,155782,Aaron Cresswell,1989-12-15 00:00:00,170.18,146,1989

          height      weight   人数
year
1967  185.420000  161.000000    1
1968  185.420000  187.000000    1
1969  184.996667  184.166667    6
1970  186.901667  181.583333   12
1971  188.171667  187.666667   12
1972  185.304545  183.500000   22
1973  182.643721  171.930233   43
1974  182.187273  170.324675   77
1975  182.003363  171.433628  113
1976  182.033333  172.000000  156
1977  182.241675  170.675393  191
1978  182.174981  171.904943  263
1979  182.335188  170.802899  345
1980  182.148433  171.679724  434
1981  181.938863  169.736842  475
1982  182.181109  171.308008  487
1983  182.532569  171.573013  541
1984  181.858979  169.332784  607
1985  182.091872  170.084317  593
1986  181.677972  168.319718  710
1987  182.303047  169.339335  722
1988  182.056559  168.982544  802
1989  182.170346  168.775934  723
1990  181.672040  166.975575  696
1991  181.459199  166.304721  699
1992  181.584323  166.065319  643
1993  181.257089  165.257089  529
1994  181.170173  164.043290  462
1995  180.900181  162.268882  331
1996  180.665641  160.645299  234
1997  180.438641  159.650485  103
1998  180.763333  161.000000   24
1999  190.500000  169.666667    3

In [15]:
df = pd.read_csv('../data/match_goal.csv')
df .head(2)
# 各球队各赛季总进球数
df.groupby(['team_api_id','season'])[['team_goal']].sum()
df.groupby(['season','team_api_id'])[['team_goal']].sum()

   id  league_id     season  stage  match_api_id local  team_api_id  team_goal
0   0          1  2008/2009     24        493017  away         9987          1
1   1          1  2008/2009     24        493017  home         8203          2

                       team_goal
team_api_id season
1601        2013/2014         20
            2014/2015         23
            2015/2016         34
1773        2011/2012         32
            2012/2013         44
...                          ...
177361      2015/2016         29
188163      2015/2016         16
208931      2015/2016         21
274581      2014/2015         25
            2015/2016         36

[1382 rows x 1 columns]

                       team_goal
season    team_api_id
2008/2009 6493                11
          7819                38
          7841                 1
          7955                 1
          8066                12
...                          ...
2015/2016 158085              23
          177361              29
          188163              16
          208931              21
          274581              36

[1382 rows x 1 columns]